---
- name: Create HelloWorld.txt
  hosts: your_windows_server
  tasks:
    - name: Create an empty file
      ansible.windows.win_file:
        path: C:\\Temp\\HelloWorld.txt
        state: touch