---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: vcsa7-vcent01.mycompany.net.au 
      username: administrator@vsphere.local
      password: Bertram2569#$#
      validate_certs: False
      name: "{{ vm_name }}"
      template: Win2022_Std_GUI_Template
      datacenter: MyCompany-DC01
      folder: /
      state: poweredon
      cluster: esxi7-cluster01.mycompany.net.au
      wait_for_ip_address: yes
